name: Preview Testing

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      tests:
        description: "The output of the Cypress Tests"
        value: ${{ jobs.['cypress-test'].outputs.tests }}

  pull_request:
    branches:
      - staging

jobs:
  cypress-test:
    name: Cypress run
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps['set-tests'].outputs.['tests'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v3
        timeout-minutes: 5 # See https://github.com/actions/cache/issues/810
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install packages
        run: npm install
      # See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
      - name: Testing all pages
        id: set-tests
        run: |
          TESTS_LOG=$(npm run cy:run)
          IS_FAIL=0

          if [ "$?" -ne 0 ]; then
            IS_FAIL=1
          fi

          echo "$TESTS_LOG"
          echo "tests=${IS_FAIL}"

